import assert from "node:assert/strict";
import {describe,it} from "node:test";
import {readFile} from "node:fs/promises";
import {flatReferenceDestinations} from "../src/lib/references.ts";
import {contrastRatio,customPaletteDefaults,paletteWarnings,validPaletteTokens} from "../src/lib/theme.ts";
import {sketchFilename} from "../src/lib/sketch.ts";
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
describe("one-shot follow-up UI",()=>{
 it("flattens database taxonomy labels alphabetically with correct parent mapping",()=>{const rows=[{id:"root",name:"Zulu",parent_id:null},{id:"child",name:"Alpha",parent_id:"root"},{id:"a",name:"Alpha",parent_id:null}];const result=flatReferenceDestinations(rows);assert.deepEqual(result.map(x=>x.label),["Alpha","Zulu","Zulu / Alpha"]);assert.deepEqual(result[2],{label:"Zulu / Alpha",collectionId:"root",subcollectionId:"child"});});
 it("keeps URL-less references functional and skips URL-only behavior",async()=>{const [content,actions,card,pages]=await Promise.all([read("src/lib/content.ts"),read("src/app/(portal)/content-actions.ts"),read("src/components/reference-card.tsx"),read("src/components/content-pages.tsx")]);assert.match(content,/URL-less references/);assert.match(actions,/kind === "link" && payload\.url/);assert.match(actions,/last_checked_at:null/);assert.match(card,/str\("url"\) \?/);assert.match(pages,/Boolean\(stringify\(record\.url\)\).*RecheckReference/);});
 it("uses one flat Napkin filing destination and preserves optional source copy",async()=>{const [editor,action]=await Promise.all([read("src/components/content-editor.tsx"),read("src/app/(portal)/content-actions.ts")]);assert.match(editor,/name="filing_destination"/);assert.match(editor,/flatReferenceDestinations\(collections\)/);assert.doesNotMatch(editor,/Links and Documents require/);assert.match(action,/reference_collection_id/);assert.match(action,/reference_subcollection_id/);});
 it("fixes root mobile overflow and hides the notebook margin line",async()=>{const css=await read("src/app/globals.css");assert.match(css,/\.global-search\s*{[\s\S]*?width: auto;[\s\S]*?min-width: 0;[\s\S]*?flex: 1 1 auto;/);assert.match(css,/html\s*{[^}]*overflow-x: clip/);assert.match(css,/@media \(max-width: 560px\)[\s\S]*?\.napkin-capture::before\s*{\s*display: none/);});
 it("provides real pending archive feedback without optimistic removal",async()=>{const editor=await read("src/components/content-editor.tsx");const action=await read("src/app/(portal)/content-actions.ts");assert.match(editor,/useFormStatus\(\)/);assert.match(editor,/Archiving…/);assert.match(editor,/disabled={pending}/);assert.doesNotMatch(editor,/optimistic/i);assert.match(action,/revision_notes/);assert.match(action,/status: "archived"/);});
 it("validates palettes and warns without hard-blocking weak contrast",()=>{assert.equal(validPaletteTokens(customPaletteDefaults),true);assert.equal(validPaletteTokens({...customPaletteDefaults,junk:"#000000"}),false);assert.ok(contrastRatio("#000000","#ffffff")>20);assert.ok(paletteWarnings({...customPaletteDefaults,canvas:"#ffffff",primary_text:"#eeeeee"}).length>0);});
 it("ships three independent personal palette slots and base-theme precedence",async()=>{const [component,layout,migration]=await Promise.all([read("src/components/custom-palettes.tsx"),read("src/app/(portal)/layout.tsx"),read("supabase/migrations/202609140017_one_shot_follow_up.sql")]);assert.match(component,/\[1,2,3\]/);assert.match(component,/Save Palette/);assert.match(component,/Reset Palette/);assert.match(component,/Use site preset/);assert.match(layout,/data-custom-palette/);assert.match(migration,/primary key \(profile_id, slot\)/i);});
 it("renders local device time/date with nonblocking city-region IP lookup",async()=>{const status=await read("src/components/dashboard-status.tsx");assert.match(status,/setInterval\([^,]+,60000\)/);assert.match(status,/Intl\.DateTimeFormat/);assert.match(status,/ipwho\.is/);assert.match(status,/\.catch\(\(\)=>\{\}\)/);assert.doesNotMatch(status,/travel_profiles|geolocation\.getCurrentPosition/);});
 it("implements pointer RGBW drawing, eraser, undo, clear, and opaque PNG save",async()=>{const sketch=await read("src/components/sketch-pad.tsx");assert.match(sketch,/onPointerDown/);for(const color of ["Red","Green","Blue","White","Eraser","Undo","Clear","Save"])assert.match(sketch,new RegExp(color));assert.match(sketch,/fillStyle="#000"/);assert.match(sketch,/toDataURL\("image\/png"\)/);assert.equal(sketchFilename(new Date(2026,8,13,9,7)),"TIKI-Sketch-2026-09-13-0907.png");});
 it("keeps Production travel access independent in People & Access",async()=>{const [admin,route]=await Promise.all([read("src/app/(portal)/admin/page.tsx"),read("src/app/admin/users/update/route.ts")]);assert.match(admin,/Production travel access/);assert.match(route,/production_travel_access: productionTravelAccess/);assert.match(route,/!active \|\| role !== "admin"/);});
});
