import assert from "node:assert/strict";
import {after,before,describe,it} from "node:test";
import {readFile,readdir} from "node:fs/promises";
import {PGlite} from "@electric-sql/pglite";
import {storageFixture} from "./storage-fixture.mjs";
const db=new PGlite();
const ids={admin:"11111111-1111-4111-8111-111111111111",editor:"22222222-2222-4222-8222-222222222222",production:"33333333-3333-4333-8333-333333333333",viewer:"44444444-4444-4444-8444-444444444444",pending:"55555555-5555-4555-8555-555555555555"};
let migrationSql;
async function as(who){await db.exec("reset role");await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[who]]);await db.exec("set role authenticated");}
before(async()=>{await db.exec(`create role authenticated;create role anon;create role service_role;create schema auth;alter default privileges grant execute on functions to anon,authenticated,service_role;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}'::jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);await storageFixture(db);const directory=new URL("../supabase/migrations/",import.meta.url);for(const name of (await readdir(directory)).filter(n=>n.endsWith(".sql")).sort()){const sql=await readFile(new URL(name,directory),"utf8");await db.exec(sql);if(name.includes("0017"))migrationSql=sql;}for(const [role,id] of Object.entries(ids)){await db.query("insert into auth.users(id,email) values($1,$2)",[id,`${role}@test.invalid`]);await db.query("update public.profiles set full_name=$1,role=$2::public.app_role,active=$3,production_travel_access=$4 where id=$5",[`${role} Person`,role==="pending"?"viewer":role==="production"?"viewer":role,role!=="pending",role==="production",id]);}});
after(async()=>db.close());
describe("one-shot follow-up database and RLS",()=>{
 it("adds private-by-default sharing and preserves owner-only base rows",async()=>{await db.query("insert into public.travel_profiles(user_id,name,details,flighty_url) values($1,'Viewer Traveler','Seat 2A','https://flighty.com/x')",[ids.viewer]);const row=(await db.query("select share_flighty,share_booking from public.travel_profiles where user_id=$1",[ids.viewer])).rows[0];assert.deepEqual(row,{share_flighty:false,share_booking:false});await as("admin");assert.equal((await db.query("select * from public.travel_profiles where user_id=$1",[ids.viewer])).rows.length,0);assert.equal((await db.query("select * from public.shared_booking_profiles()")).rows.length,0);});
 it("scopes Flighty to active members and booking prefs to Production/Admin with explicit sharing",async()=>{await as("viewer");await db.query("update public.travel_profiles set share_flighty=true,share_booking=true where user_id=$1",[ids.viewer]);await as("editor");assert.equal((await db.query("select * from public.shared_flighty_profiles() where profile_id=$1",[ids.viewer])).rows.length,1);assert.equal((await db.query("select * from public.shared_booking_profiles()")).rows.length,0);await as("production");assert.equal((await db.query("select details from public.shared_booking_profiles() where profile_id=$1",[ids.viewer])).rows[0].details,"Seat 2A");await as("admin");assert.equal((await db.query("select * from public.shared_booking_profiles() where profile_id=$1",[ids.viewer])).rows.length,1);await db.exec("reset role");await db.query("update public.profiles set active=false where id=$1",[ids.viewer]);await as("admin");assert.equal((await db.query("select * from public.shared_booking_profiles() where profile_id=$1",[ids.viewer])).rows.length,0);await db.exec("reset role");await db.query("update public.profiles set active=true where id=$1",[ids.viewer]);});
 it("denies anonymous/inactive callers and prevents capability self-grant",async()=>{await as("viewer");assert.equal((await db.query("update public.profiles set production_travel_access=true where id=$1 returning id",[ids.viewer])).rows.length,0);await as("pending");for(const sql of ["select * from public.shared_flighty_profiles()","select * from public.shared_booking_profiles()"] )assert.equal((await db.query(sql)).rows.length,0);await db.exec("reset role;set role anon");for(const sql of ["select * from public.shared_flighty_profiles()","select * from public.shared_booking_profiles()"] )await assert.rejects(()=>db.query(sql),e=>e.code==="42501");});
 it("stores exactly three independent owner-only palette slots with constrained tokens",async()=>{const tokens={canvas:"#111111",surface:"#222222",primary_accent:"#33aabb",secondary_accent:"#cc5533",primary_text:"#ffffff",muted_text:"#bbbbbb"};await as("viewer");await db.query("insert into public.user_custom_palettes(profile_id,slot,name,tokens) values($1,1,'Road',$2),($1,2,'Shop',$2)",[ids.viewer,JSON.stringify(tokens)]);await db.query("update public.user_custom_palettes set name='Road Night' where profile_id=$1 and slot=1",[ids.viewer]);assert.deepEqual((await db.query("select slot,name from public.user_custom_palettes order by slot")).rows,[{slot:1,name:"Road Night"},{slot:2,name:"Shop"}]);await assert.rejects(()=>db.query("insert into public.user_custom_palettes(profile_id,slot,name,tokens) values($1,4,'Bad',$2)",[ids.viewer,JSON.stringify(tokens)]));await assert.rejects(()=>db.query("insert into public.user_custom_palettes(profile_id,slot,name,tokens) values($1,3,'Bad',$2)",[ids.viewer,JSON.stringify({...tokens,junk:"#000000"})]));await as("editor");assert.equal((await db.query("select * from public.user_custom_palettes where profile_id=$1",[ids.viewer])).rows.length,0);});
 it("files URL-less and URL-backed Napkins into exact flat taxonomy with tags and provenance",async()=>{await as("editor");const tag=(await db.query("insert into public.tags(name,slug) values('Follow up tag','follow-up-tag') returning id")).rows[0].id;for(const [source,collection,sub] of [[null,"control-systems","consoles"],["https://example.com","unsorted",null]]){const note=(await db.query("insert into public.napkin_notes(body,source_url,status,created_by) values('Useful note',$1,'raw',$2) returning id",[source,ids.editor])).rows[0].id;await db.query("insert into public.content_tags(tag_id,entity_kind,entity_id,created_by) values($1,'napkin',$2,$3)",[tag,note,ids.editor]);const filed=(await db.query("select * from public.file_napkin($1,'link','Filed reference','Reviewed',$2,$3)",[note,collection,sub])).rows[0];const link=(await db.query("select url,collection_id,subcollection_id,status from public.link_items where id=$1",[filed.entity_id])).rows[0];assert.deepEqual(link,{url:source,collection_id:collection,subcollection_id:sub,status:"published"});assert.equal((await db.query("select count(*) count from public.content_tags where entity_kind='link' and entity_id=$1",[filed.entity_id])).rows[0].count,1);assert.equal((await db.query("select count(*) count from public.revision_notes where entity_id in ($1,$2)",[note,filed.entity_id])).rows[0].count,2);}}
 );
 it("keeps the forward migration idempotent and function grants narrow",async()=>{await db.exec("reset role");await db.exec(migrationSql);for(const signature of ["shared_flighty_profiles()","shared_booking_profiles()","file_napkin(uuid,relationship_kind,text,text,text,text)"]){const row=(await db.query("select prosecdef,proconfig,has_function_privilege('anon',oid,'execute') anon,has_function_privilege('authenticated',oid,'execute') member,has_function_privilege('service_role',oid,'execute') service from pg_proc where oid=$1::regprocedure",[`public.${signature}`])).rows[0];assert.equal(row.prosecdef,true);assert.deepEqual(row.proconfig,["search_path=\"\""]);assert.deepEqual([row.anon,row.member,row.service],[false,true,false]);}});
});
