"use client";
import { useEffect,useRef,useState } from "react";
import { Download,Eraser,RotateCcw,Trash2 } from "lucide-react";
import { sketchFilename } from "@/lib/sketch";
const tools=[{name:"Red",color:"#ff3b30"},{name:"Green",color:"#34c759"},{name:"Blue",color:"#168bff"},{name:"White",color:"#ffffff"}] as const;
export function SketchPad(){const canvasRef=useRef<HTMLCanvasElement>(null);const history=useRef<ImageData[]>([]);const drawing=useRef(false);const [tool,setTool]=useState<string>("White");
 const context=()=>canvasRef.current?.getContext("2d",{willReadFrequently:true})??null;
 const black=()=>{const c=canvasRef.current,x=context();if(c&&x){x.fillStyle="#000";x.fillRect(0,0,c.width,c.height)}};
 useEffect(()=>{const c=canvasRef.current;if(!c)return; const resize=()=>{const old=document.createElement("canvas");old.width=c.width;old.height=c.height;old.getContext("2d")?.drawImage(c,0,0);const rect=c.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);c.width=Math.max(1,Math.round(rect.width*dpr));c.height=Math.max(1,Math.round(rect.height*dpr));const x=c.getContext("2d");x!.fillStyle="#000";x!.fillRect(0,0,c.width,c.height);if(old.width)x?.drawImage(old,0,0,c.width,c.height)};resize();const observer=new ResizeObserver(resize);observer.observe(c);return()=>observer.disconnect()},[]);
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const c=canvasRef.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{const c=canvasRef.current!,x=context();if(!x)return;history.current.push(x.getImageData(0,0,c.width,c.height));if(history.current.length>30)history.current.shift();drawing.current=true;c.setPointerCapture(e.pointerId);const p=point(e);x.beginPath();x.moveTo(p.x,p.y)};
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const c=canvasRef.current!,x=context();if(!x)return;const p=point(e),scale=c.width/1000;x.lineCap="round";x.lineJoin="round";x.strokeStyle=tool==="Eraser"?"#000":tools.find(t=>t.name===tool)?.color??"#fff";x.lineWidth=(tool==="Eraser"?16:6)*scale;x.lineTo(p.x,p.y);x.stroke()};
 const end=()=>{drawing.current=false}; const undo=()=>{const x=context(),last=history.current.pop();if(x&&last)x.putImageData(last,0,0)}; const clear=()=>{const c=canvasRef.current,x=context();if(c&&x){history.current.push(x.getImageData(0,0,c.width,c.height));black()}};
 const save=()=>{const c=canvasRef.current;if(!c)return;const exportCanvas=document.createElement("canvas");exportCanvas.width=c.width;exportCanvas.height=c.height;const x=exportCanvas.getContext("2d")!;x.fillStyle="#000";x.fillRect(0,0,c.width,c.height);x.drawImage(c,0,0);const a=document.createElement("a");a.download=sketchFilename();a.href=exportCanvas.toDataURL("image/png");a.click()};
 return <div className="sketch-pad"><div className="sketch-tools" role="toolbar" aria-label="Drawing tools">{tools.map(item=><button type="button" aria-pressed={tool===item.name} onClick={()=>setTool(item.name)} key={item.name}><i style={{background:item.color}}/>{item.name}</button>)}<button type="button" aria-pressed={tool==="Eraser"} onClick={()=>setTool("Eraser")}><Eraser size={16}/>Eraser</button><button type="button" onClick={undo}><RotateCcw size={16}/>Undo</button><button type="button" onClick={clear}><Trash2 size={16}/>Clear</button><button type="button" onClick={save}><Download size={16}/>Save</button></div><canvas ref={canvasRef} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} aria-label="Black sketch canvas"/></div>}
